### ISSUE TITLE
Crash with Android (OpenCV init issue)

### ISSUE THREAD

**Issue by jmazier-j2d** [WebsiteBeaver/react-native-document-scanner-plugin#10]
Hello !

I'm experiencing an issue with Open CV initialization on many different Android devices (seems to be somehow link with android 12's devices).

![image](https://user-images.githubusercontent.com/48437234/196179838-d0aa9290-b7ac-4394-ac3b-c46189721c25.png)

I'm capturing the picture and when pressing the tick button to validate the scan, the crash happen

![image](https://user-images.githubusercontent.com/48437234/196180006-f1ec30aa-7adf-4261-87cf-46e04ad553f2.png)

I've found other dev experiencing similar issue on different implementation of OpenCV under android and it looks like there some kind of pre-init to run in order to avoid it... still trying to dig into this issue, will keep updating here if I find a solution.

**Comment by dmarcs** [comment]
This can happen if you change orientation (portrait to landscape for example). It's fixed in https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/tree/0.1.2.

https://github.com/WebsiteBeaver/android-document-scanner/commit/81420c8cdfb35b2a972dff4b6ec592bfb3e53604
Prevent the app from crashing due to an activity restart on orientation change
