### ISSUE TITLE
Issue with cropping default on Android

### ISSUE THREAD

**Issue by jlump001** [WebsiteBeaver/react-native-document-scanner-plugin#11]
When scanning on Android, the four default crop points are nearly hidden and stacked on the upper left side of the screen. I assume this happens when it doesn't find a square/rectangle? I did some testing and this only ever occurs on the first scan because if I click the '+' icon after initial scan it will do the four points in four corners.

**Comment by dmarcs** [comment]
can you add a screenshot?

**Comment by Lump001** [comment]
![image](https://user-images.githubusercontent.com/97997713/196956520-18cbe155-641e-4770-b56c-42e74c2b4a78.jpeg)

**Comment by Lump001** [comment]
The crop points are on the left side of the screen stacked on each other.

**Comment by davidnovalogix** [comment]
Im having the exact same issue

**Comment by dmarcs** [comment]
What phone and Android version is that?

**Comment by Lump001** [comment]
I will get to you tomorrow. Currently not at work.

**Comment by jlump001** [comment]
Android Version - 8.1.0
moto e5 (XT1920DL)

**Comment by dmarcs** [comment]
I'll see if I can reproduce on my emulator. I wonder if you get the same problem on an newer Android version

**Comment by dmarcs** [comment]
fixed in https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/tree/0.1.2

https://github.com/WebsiteBeaver/android-document-scanner/commit/92baa3350133b1456d0c0c983fa8cbc96b0b0ac1
On some Android phones the image preview width and height aren't available until later, so we need to calculate the width and height ahead of time.
